### ISSUE TITLE
Support extending country list

### ISSUE THREAD

**Issue by niemyjski** [janmarques/IsoCountries#2]
Countries will be added over time like `Kosovo` and other write ins.

`Note: Kosovo is not listed as an ISO standard country. The unofficial 2 and 3-digit codes are used by the European Commission and others until Kosovo is assigned an ISO code.	XK	XKX`

https://countrycode.org/kosovo
https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/D_Country%2C_State%2C_and_Province_Codes/A_Country_Names_and_Their_ISO_Codes
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

**Comment by niemyjski** [comment]
Currently the country constructor is private, which prevents extending the lists.

**Comment by janmarques** [comment]
@niemyjski will add extensibility support

**Comment by janmarques** [comment]
@niemyjski have a look here https://github.com/janmarques/IsoCountries/blob/master/CountryTests/CountryExtensibilityTests.cs

You should be able to add countries as you wish. Let me know if it's OK, then I'll close this issue

**Comment by niemyjski** [comment]
Yes that works great :D
